// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2bOFnV5IEOanGSEHdcUupJJsc4Nl9aQ',
    appId: '1:14650306357:web:5bfa1eca8dcd958cd7267c',
    messagingSenderId: '14650306357',
    projectId: 'work-assignment-ef4ae',
    authDomain: 'work-assignment-ef4ae.firebaseapp.com',
    storageBucket: 'work-assignment-ef4ae.appspot.com',
    measurementId: 'G-FWY2483NFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPrLuxWdvIQ4oL0pb8p2AkH20rh4tb4c',
    appId: '1:14650306357:android:93b876d7f9359e46d7267c',
    messagingSenderId: '14650306357',
    projectId: 'work-assignment-ef4ae',
    storageBucket: 'work-assignment-ef4ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJqNQfdncFBC8gNxTemRUDd1oMy8fWLk',
    appId: '1:14650306357:ios:edb382329aaccc1dd7267c',
    messagingSenderId: '14650306357',
    projectId: 'work-assignment-ef4ae',
    storageBucket: 'work-assignment-ef4ae.appspot.com',
    androidClientId: '14650306357-28665akdp51jgidcep3n1e4q8dl60642.apps.googleusercontent.com',
    iosClientId: '14650306357-hk4r1i37gpegb09ucohu50id8n1r1hc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.workAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGJqNQfdncFBC8gNxTemRUDd1oMy8fWLk',
    appId: '1:14650306357:ios:edb382329aaccc1dd7267c',
    messagingSenderId: '14650306357',
    projectId: 'work-assignment-ef4ae',
    storageBucket: 'work-assignment-ef4ae.appspot.com',
    androidClientId: '14650306357-28665akdp51jgidcep3n1e4q8dl60642.apps.googleusercontent.com',
    iosClientId: '14650306357-hk4r1i37gpegb09ucohu50id8n1r1hc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.workAssignment',
  );
}
